### ISSUE TITLE
Fix useEffects so they only run when needed

### ISSUE THREAD

**Issue by nikobatzi1990** [nikobatzi1990/meltdown-tracker_work-in-progress#65]
Right now, the useEffects have no dependency arrays which means they are constantly being run. Adding dependency arrays would cause problems since the data arrays aren't always populated with necessary data on time for other functions to be executed. The following components need to be fixed so the useEffects work asynchronously:

- [x] Taglist
- [x] Entrylist

**Comment by anmol111pal** [comment]
Need more info about the expected behaviour. @nikobatzi1990

**Comment by anmol111pal** [comment]
hey @nikobatzi1990 , kindly review this & merge it.
